"""Doc add name

Revision ID: 0409bd4cb700
Revises: 01baab2d6b4b
Create Date: 2023-09-18 20:41:48.761679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0409bd4cb700'
down_revision: Union[str, None] = '01baab2d6b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('docs', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('docs', 'name')
    # ### end Alembic commands ###
