version: '3.9'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  columbot:
    image: timvladislav13010/columbot:latest
    ports:
      - "8000:8000"
    env_file:
      - .env