version: '3.9'
services:
  postgres:
    image: postgres:12
    env_file:
      - ../.env
    ports:
      - "5432:5432"
  columbot:
    image: timvladislav13010/columbot:latest
    ports:
      - "8000:8000"
    env_file:
      - ../.env